# all:	ft

ft_map:
	@clang++ -Wall -Wextra -Werror -D STL=0 main_map.cpp

stl_map:
	@clang++ -Wall -Wextra -Werror -D STL=1 main_map.cpp

ft_vector:
	@clang++ -Wall -Wextra -Werror -D STL=0 main_vector.cpp

stl_vector:
	@clang++ -Wall -Wextra -Werror -D STL=1 main_vector.cpp

ft_stack:
	@clang++ -Wall -Wextra -Werror -D STL=0 main_stack.cpp

stl_stack:
	@clang++ -Wall -Wextra -Werror -D STL=1 main_stack.cpp


