all:
	@clang++ -Wall -Wextra -Werror mains/ft_main_vector.cpp -o ft_vector
	@clang++ -Wall -Wextra -Werror mains/std_main_vector.cpp -o std_vector

time:
	@clang++ mains/ft_main_vector_time.cpp -o time_ft_vector
	@clang++ mains/std_main_vector_time.cpp -o time_std_vector

clean:
	@rm -rf ft_vector std_vector time_ft_vector time_std_vector

ft:
	@clang++ -Wall -Wextra -Werror mains/ft_main_vector.cpp -o ft_vector
	
std:
	@clang++ -Wall -Wextra -Werror mains/std_main_vector.cpp -o std_vector